apiVersion: apps/v1
kind: Deployment
metadata:
  name: enroller-api
  labels:
    app: enroller-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enroller-api
  template:
    metadata:
      labels:
        app: enroller-api
    spec:
      volumes:
        - name: rcaadmin-msp
          secret:
            secretName: rcaadmin-msp
            items:
              - key: cacerts/cacert.pem
                path: cacerts/cacert.pem
              - key: keystore/key.pem
                path: keystore/key.pem
              - key: signcerts/cert.pem
                path: signcerts/cert.pem
        - name: tls-certs
          secret:
            secretName: tls-certs
      containers:
        - name: enroller-api
          image: localhost:5000/enroller-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: token
          volumeMounts:
            - name: rcaadmin-msp
              mountPath: /etc/rcaadmin/msp
              readOnly: true
            - name: tls-certs
              mountPath: /etc/tls/tls-cert.pem
              subPath: tls-cert.pem
              readOnly: true
---
kind: Service
apiVersion: v1
metadata:
  name: enroller-api
spec:
  selector:
    app: enroller-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enroller-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 60s
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  # labels:
  #   app: enroller-api
  #   app.kubernetes.io/instance: fabricpeer
  #   app.kubernetes.io/managed-by: fabric-operator
  #   app.kubernetes.io/name: fabric
  #   creator: fabric
  #   orgname: Org1MSP
spec:
  ingressClassName: nginx
  rules:
    - host: enrollerapi.localho.st
      http:
        paths:
          - backend:
              service:
                name: enroller-api
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - enrollerapi.localho.st